name: Build and  Push Frontend & Backend Docker Images

on: 
    push:
        branches: ["main"]

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            # Build and push Backend Docker image
            - name: Build Backend Image
              run: |
                docker build -t ${{ secrets.DOCKER_USERNAME }}/saas-notes-backend:latest -f backend/Dockerfile ./backend

            - name: Push Backend Image
              run: |
               docker push ${{ secrets.DOCKER_USERNAME }}/saas-notes-backend:latest

            # Build and push Frontend Docker image
            - name: Build Frontend Image
              run: |
                docker build -t ${{ secrets.DOCKER_USERNAME }}/saas-notes-frontend:latest -f frontend/Dockerfile ./frontend 

            - name: Push Frontend Image
              run: |
               docker push ${{ secrets.DOCKER_USERNAME }}/saas-notes-frontend:latest  